name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop


jobs:
  maven_build:
    uses: suppada/java-app/.github/workflows/maven_build.yml@main
    with:
      java_version: '21'
      enable_release: true
      tag_name: 'latest-build'
    permissions:
      contents: write
      packages: read
  codeql_analysis:
    needs: maven_build
    uses: suppada/java-app/.github/workflows/codeql_analysis.yml@main
    with:
      maven_build_status: ${{ needs.maven_build.result }}
    if: ${{ needs.maven_build.result == 'success' }}
    permissions:
      security-events: write # Allowing write access to security events in the calling workflow
      actions: read         # Allowing read access to actions in the calling workflow
      contents: read
  docker_build:
    needs: codeql_analysis
    uses: suppada/java-app/.github/workflows/docker_build.yml@main
    with:
      image_name: ${{ github.repository }}
      registry: ghcr.io
      artifact_filename: 'maven'  # Name of the artifact (without extension)
      artifact_extension: '.war'
    permissions:
      contents: read
      packages: write