name: Maven Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    uses: suppada/java-app/.github/workflows/maven_build.yml@main
    with:
      java_version: '21'
      maven_goals: 'package'
      enable_release: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}