name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
jobs:
  maven_build:
    uses: suppada/java-app/.github/workflows/maven_build.yml@main
    with:
      java_version: '21'
      enable_release: true
    permissions:
      contents: write
      packages: read
  codeql_analysis:
    needs: maven_build  # Ensures CodeQL analysis runs after docker_build
    uses: suppada/java-app/.github/workflows/codeql_analysis.yml@main
    if: ${{ needs.maven_build.result }}
  docker_build:
    needs: codeql_analysis
    uses: suppada/java-app/.github/workflows/docker_build.yml@main
    with:
      image_name: ${{ github.repository }}
      registry: ghcr.io
    permissions:
      contents: read  
      packages: write  # Passing status from the Maven build job